//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasierAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> SelectedCount { get; set; }
        public Nullable<bool> IsTrue { get; set; }
        public string Message { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
