//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasierAPI.Areas.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionComment
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public int UserId { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
